###LOCAL
### Get all books
GET http://localhost:8080/books

### Get book by ID
GET http://localhost:8080/books/67a82993490d647f67cd4326

### Get book by ID
GET http://localhost:8080/books/67a82993490d647f67cd4327

### Get book by ID
GET http://localhost:8080/books/67a82993490d647f67cd4328

### Add Book
POST http://localhost:8080/books HTTP/1.1
Content-Type: application/json

{
  "title": "France's Journey",
  "author": "France Doe",
  "isbn": "978-1234567891",
  "publishedDate": "1990-01-01",
  "genre": "Biography"
}

### Update Book
PUT http://localhost:8080/books/67a847f57b35e7cca2e025ef HTTP/1.1
Content-Type: application/json

{
  "title": "Lena's World",
  "author": "Lena Doe",
  "isbn": "978-0987654322",
  "publishedDate": "1991-02-02",
  "genre": "Fantasy"
}

### Delete Book
DELETE http://localhost:8080/books/67a847f57b35e7cca2e025ef HTTP/1.1


###RENDER
### Get all books
GET https://cse341-5-8-project.onrender.com/books

### Get book by ID
GET https://cse341-5-8-project.onrender.com/books/67a82993490d647f67cd4326

### Get book by ID
GET https://cse341-5-8-project.onrender.com/books/67a82993490d647f67cd4327

### Get book by ID
GET https://cse341-5-8-project.onrender.com/books/67a82993490d647f67cd4328

### Add Book
POST https://cse341-5-8-project.onrender.com/books
Content-Type: application/json

{
  "title": "France's Journey",
  "author": "France Doe",
  "isbn": "978-1234567891",
  "publishedDate": "1990-01-01",
  "genre": "Biography"
}

### Update Book
PUT https://cse341-5-8-project.onrender.com/books/67a84854e8b6adb9ef28d729
Content-Type: application/json

{
  "title": "Lena's World",
  "author": "Lena Doe",
  "isbn": "978-0987654322",
  "publishedDate": "1991-02-02",
  "genre": "Fantasy"
}

### Delete Book
DELETE https://cse341-5-8-project.onrender.com/books/67a84854e8b6adb9ef28d729
